linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gofmt
    - goimports
    - revive
    - gosec
    - prealloc

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: blank-imports
      - name: exported
      - name: unreachable-code
      - name: unused-parameter

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
