version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/genbu
    ldflags:
      - -s -w -X github.com/dreadnought-inc/genbu/internal/cli.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

dockers:
  - image_templates:
      - "dninc/genbu:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.goreleaser
    goarch: amd64

  - image_templates:
      - "dninc/genbu:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    dockerfile: Dockerfile.goreleaser
    goarch: arm64

docker_manifests:
  - name_template: "dninc/genbu:{{ .Version }}"
    image_templates:
      - "dninc/genbu:{{ .Version }}-amd64"
      - "dninc/genbu:{{ .Version }}-arm64"

  - name_template: "dninc/genbu:latest"
    image_templates:
      - "dninc/genbu:{{ .Version }}-amd64"
      - "dninc/genbu:{{ .Version }}-arm64"
